apiVersion: batch/v1
kind: Job
metadata:
  name: dl-videos
spec:
  parallelism: 3
  template:
    metadata:
      name: dl-videos
    spec:
      containers:
        - name: worker
          image: gcr.io/wc-personal/worker
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.5
      restartPolicy: OnFailure
